-- EuroLeague 2025-26 full rosters
INSERT INTO players (id, name, league, active) VALUES
  -- Real Madrid
  (gen_random_uuid(), 'Facundo Campazzo', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Theo Maledon', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Sergio Llull', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Andres Feliz', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Trey Lyles', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'David Kramer', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Alberto Abalde', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Gabriele Procida', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Mario Hezonja', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Izan Almansa', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Gabriel Deck', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Chuma Okeke', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Usman Garuba', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Walter Tavares', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Alex Len', 'EUROLEAGUE', true),
  -- FC Barcelona
  (gen_random_uuid(), 'Kevin Punter', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Juani Marcos', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Dario Brizuela', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Tomas Satoransky', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Juan Nunez', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nicolas Laprovittola', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Myles Cale', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Miles Norris', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Will Clyburn', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Joel Parra', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Jan Vesely', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Willy Hernangomez', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Tornike Shengelia', 'EUROLEAGUE', true),
  -- Panathinaikos AKTOR Athens
  (gen_random_uuid(), 'TJ Shorts', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Panagiotis Kalaitzakis', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Kostas Sloukas', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Jerian Grant', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Kendrick Nunn', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Vassilis Toliopoulos', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Cedi Osman', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nigel Hayes-Davis', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Juancho Hernangomez', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Mathias Lessort', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Kenneth Faried', 'EUROLEAGUE', true),

  -- Fenerbahce Beko Istanbul
  (gen_random_uuid(), 'Wade Baldwin IV', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Talen Horton Tucker', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Melih Mahmutoglu', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Brandon Boston Jr.', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nando De Colo', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Devon Hall', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Metecan Birsen', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nicolo Melli', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Tarik Biberovic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Onuralp Bitim', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Mikael Jantunen', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Bonzie Colson', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Armando Bacot Jr.', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Chris Silva', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Khem Birch', 'EUROLEAGUE', true),
  -- Olympiacos Piraeus
  (gen_random_uuid(), 'Thomas Walkup', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Frank Ntilikina', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Giannoulis Larentzakis', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Monte Morris', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Tyler Dorsey', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Cory Joseph', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Tyson Ward', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Sasha Vezenkov', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Kostas Papanikolaou', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Alec Peters', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Evan Fournier', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Moustapha Fall', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nikola Milutinov', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Donta Hall', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Tyrique Jones', 'EUROLEAGUE', true),
  -- Anadolu Efes Istanbul
  (gen_random_uuid(), 'Shane Larkin', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Rodrigue Beaubois', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Jordan Loyd', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Saben Lee', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Rolands Smits', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Cole Swider', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Erkan Yilmaz', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Georgios Papagiannis', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Vincent Poirier', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Kai Jones', 'EUROLEAGUE', true),
  -- AS Monaco
  (gen_random_uuid(), 'Elie Okobo', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Terry Tarpey', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nemanja Nedovic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Matthew Strazel', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Mike James', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Jaron Blossomgame', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Alpha Diallo', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Juhann Begarin', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Daniel Theis', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nikola Mirotic', 'EUROLEAGUE', true),
  -- Crvena Zvezda Meridianbet Belgrade
  (gen_random_uuid(), 'Codi Miller-McIntyre', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Isaiah Canaan', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Jared Butler', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Tyson Carter', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Aleksej Nedeljkovic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Dejan Davidovac', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nikola Kalinic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Ognjen Dobric', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Jordan Nwora', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Semi Ojeleye', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Jasiel Rivero', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Donatas Motiejunas', 'EUROLEAGUE', true),
  -- Dubai Basketball
  (gen_random_uuid(), 'Nate Mason', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Aleksa Avramovic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Klemen Prepelic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Dzanan Musa', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'McKinley Wright IV', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nemanja Dangubic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Dwayne Bacon', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Awudu Abass', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Davis Bertans', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Justin Anderson', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Filip Petrusev', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Bruno Caboclo', 'EUROLEAGUE', true),
  -- EA7 Emporio Armani Milan
  (gen_random_uuid(), 'Niccolo Mannion', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Lorenzo Brown', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Stefano Tonut', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Leandro Bolmaro', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Zach LeDay', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Giampaolo Ricci', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Shavon Shields', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Devin Booker', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Josh Nebo', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Bryant Dunston', 'EUROLEAGUE', true),
  -- FC Bayern Munich
  (gen_random_uuid(), 'Neno Dimitrijevic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Andreas Obst', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Stefan Jovic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Justus Hollatz', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Oscar Da Silva', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Niels Giffey', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Vladimir Lucic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Isiaha Mike', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Johannes Voigtmann', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Wenyen Gabriel', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'David McCormack', 'EUROLEAGUE', true),
  -- Hapoel IBI Tel Aviv
  (gen_random_uuid(), 'Chris Jones', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Antonio Blakeney', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Elijah Bryant', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Vasilije Micic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Kessler Edwards', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Levi Randolph', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Ish Wainright', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Johnathan Motley', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Tai Odiase', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Dan Oturu', 'EUROLEAGUE', true),
  -- Kosner Baskonia Vitoria-Gasteiz
  (gen_random_uuid(), 'Markus Howard', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Markquis Nowell', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Matteo Spagnolo', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Trent Forrest', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Rodions Kurucs', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Tadas Sedekerskis', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Timothe Luwawu-Cabarrot', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Mamadi Diakite', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Khalifa Diop', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Chiek Diallo', 'EUROLEAGUE', true),
  -- LDLC ASVEL Villeurbanne
  (gen_random_uuid(), 'Thomas Heurtel', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Glynn Watson', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Shaquille Harrison', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Braian Angola', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Edwin Jackson', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'David Lighty', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Paul Eboua', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Mbaye Ndiaye', 'EUROLEAGUE', true),
  -- Maccabi Rapyd Tel Aviv
  (gen_random_uuid(), 'Iffe Lundberg', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Lonnie Walker IV', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'John DiBartolomeo', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Jaylen Hoard', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Roman Sorkin', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'William Rayman', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Marcio Santos', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Zachary Hankins', 'EUROLEAGUE', true),
  -- Paris Basketball
  (gen_random_uuid(), 'Nadir Hifi', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Justin Robinson', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Joel Ayayi', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Yakuba Ouattara', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Lamar Stevens', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Jeremy Morgan', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Amath M''Baye', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Derek Willis', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Allan Dokossi', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Mouhamed Faye', 'EUROLEAGUE', true),
  -- Partizan Mozzart Bet Belgrade
  (gen_random_uuid(), 'Carlik Jones', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Shake Milton', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Duane Washington', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nick Calathes', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Dylan Osetkowski', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Mario Nakic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Vanja Marinkovic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Aleksej Pokusevski', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Tonye Jekiri', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Bruno Fernando', 'EUROLEAGUE', true),
  -- Valencia Basket
  (gen_random_uuid(), 'Brancou Badio', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Jean Montero', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Xabi Lopez-Arostegui', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Kameron Taylor', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nathan Reuvers', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Braxton Key', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Jaime Pradilla', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Matthew Costello', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Yankuba Sima', 'EUROLEAGUE', true),
  -- Virtus Bologna
  (gen_random_uuid(), 'Luca Vildoza', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Carsen Edwards', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Alessandro Pajola', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Daniel Hackett', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Alen Smailagic', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Derrick Alston Jr.', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Karim Jallow', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Nicola Akele', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Mouhamet Diouf', 'EUROLEAGUE', true),
  -- Zalgiris Kaunas
  (gen_random_uuid(), 'Nigel Williams-Goss', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Sylvain Francisco', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Dovydas Giedraitis', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Maodo Lo', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Ignas Brazdeikis', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Azuolas Tubelis', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Edgaras Ulanovas', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Moses Wright', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Laurynas Birutis', 'EUROLEAGUE', true),
  (gen_random_uuid(), 'Dominykas Daubaris', 'EUROLEAGUE', true);
