-- NBA players 2025-26 season
INSERT INTO players (id, name, league, active) VALUES



  -- Atlanta Hawks
  (gen_random_uuid(), 'Jalen Johnson', 'NBA', true),
  (gen_random_uuid(), 'Nickeil Alexander-Walker', 'NBA', true),
  (gen_random_uuid(), 'Dyson Daniels', 'NBA', true),
  (gen_random_uuid(), 'Onyeka Okongwu', 'NBA', true),
  (gen_random_uuid(), 'Zaccharie Risacher', 'NBA', true),
  (gen_random_uuid(), 'Keaton Wallace', 'NBA', true),
  (gen_random_uuid(), 'Asa Newell', 'NBA', true),
  (gen_random_uuid(), 'Caleb Houstan', 'NBA', true),
  (gen_random_uuid(), 'Mouhamed Gueye', 'NBA', true),
  (gen_random_uuid(), 'N''Faly Dante', 'NBA', true),
  -- Boston Celtics
  (gen_random_uuid(), 'Jaylen Brown', 'NBA', true),
  (gen_random_uuid(), 'Jayson Tatum', 'NBA', true),
  (gen_random_uuid(), 'Derrick White', 'NBA', true),
  (gen_random_uuid(), 'Payton Pritchard', 'NBA', true),
  (gen_random_uuid(), 'Sam Hauser', 'NBA', true),
  (gen_random_uuid(), 'Neemias Queta', 'NBA', true),
  (gen_random_uuid(), 'Baylor Scheierman', 'NBA', true),
  (gen_random_uuid(), 'Jordan Walsh', 'NBA', true),
  (gen_random_uuid(), 'Hugo González', 'NBA', true),
  (gen_random_uuid(), 'Luka Garza', 'NBA', true),
  (gen_random_uuid(), 'Josh Minott', 'NBA', true),
  (gen_random_uuid(), 'Nikola Vučević', 'NBA', true),
  (gen_random_uuid(), 'Anfernee Simons', 'NBA', true),
  (gen_random_uuid(), 'Ron Harper Jr.', 'NBA', true),
  -- Brooklyn Nets
  (gen_random_uuid(), 'Nic Claxton', 'NBA', true),
  (gen_random_uuid(), 'Cam Thomas', 'NBA', true),
  (gen_random_uuid(), 'Noah Clowney', 'NBA', true),
  (gen_random_uuid(), 'Terance Mann', 'NBA', true),
  (gen_random_uuid(), 'Egor Dëmin', 'NBA', true),
  (gen_random_uuid(), 'Ziaire Williams', 'NBA', true),
  (gen_random_uuid(), 'Drake Powell', 'NBA', true),
  (gen_random_uuid(), 'Nolan Traoré', 'NBA', true),
  (gen_random_uuid(), 'Danny Wolf', 'NBA', true),
  (gen_random_uuid(), 'Day''Ron Sharpe', 'NBA', true),
  (gen_random_uuid(), 'Ben Saraf', 'NBA', true),
  (gen_random_uuid(), 'Jalen Wilson', 'NBA', true),
  (gen_random_uuid(), 'Ochai Agbaji', 'NBA', true),
  (gen_random_uuid(), 'Tyrese Martin', 'NBA', true),
  (gen_random_uuid(), 'Michael Porter Jr.', 'NBA', true),
  -- Charlotte Hornets
  (gen_random_uuid(), 'LaMelo Ball', 'NBA', true),
  (gen_random_uuid(), 'Miles Bridges', 'NBA', true),
  (gen_random_uuid(), 'Brandon Miller', 'NBA', true),
  (gen_random_uuid(), 'Kon Knueppel', 'NBA', true),
  (gen_random_uuid(), 'Moussa Diabaté', 'NBA', true),
  (gen_random_uuid(), 'Sion James', 'NBA', true),
  (gen_random_uuid(), 'Ryan Kalkbrenner', 'NBA', true),
  (gen_random_uuid(), 'Collin Sexton', 'NBA', true),
  (gen_random_uuid(), 'Josh Green', 'NBA', true),
  (gen_random_uuid(), 'Tre Mann', 'NBA', true),
  (gen_random_uuid(), 'Grant Williams', 'NBA', true),
  (gen_random_uuid(), 'Tidjane Salaün', 'NBA', true),
  (gen_random_uuid(), 'Liam McNeeley', 'NBA', true),
  (gen_random_uuid(), 'Coby White', 'NBA', true),
  (gen_random_uuid(), 'Pat Connaughton', 'NBA', true),
  (gen_random_uuid(), 'KJ Simpson', 'NBA', true),
  -- Chicago Bulls
  (gen_random_uuid(), 'Josh Giddey', 'NBA', true),
  (gen_random_uuid(), 'Isaac Okoro', 'NBA', true),
  (gen_random_uuid(), 'Tre Jones', 'NBA', true),
  (gen_random_uuid(), 'Patrick Williams', 'NBA', true),
  (gen_random_uuid(), 'Jalen Smith', 'NBA', true),
  (gen_random_uuid(), 'Guerschon Yabusele', 'NBA', true),
  (gen_random_uuid(), 'Matas Buzelis', 'NBA', true),
  (gen_random_uuid(), 'Noa Essengue', 'NBA', true),
  -- Cleveland Cavaliers
  (gen_random_uuid(), 'Donovan Mitchell', 'NBA', true),
  (gen_random_uuid(), 'Evan Mobley', 'NBA', true),
  (gen_random_uuid(), 'Jarrett Allen', 'NBA', true),
  (gen_random_uuid(), 'Jaylon Tyson', 'NBA', true),
  (gen_random_uuid(), 'Sam Merrill', 'NBA', true),
  (gen_random_uuid(), 'Dean Wade', 'NBA', true),
  (gen_random_uuid(), 'Thomas Bryant', 'NBA', true),
  (gen_random_uuid(), 'Tyrese Proctor', 'NBA', true),
  (gen_random_uuid(), 'Max Strus', 'NBA', true),
  (gen_random_uuid(), 'Craig Porter Jr.', 'NBA', true),
  (gen_random_uuid(), 'Larry Nance Jr.', 'NBA', true),
  -- Dallas Mavericks
  (gen_random_uuid(), 'Cooper Flagg', 'NBA', true),
  (gen_random_uuid(), 'Naji Marshall', 'NBA', true),
  (gen_random_uuid(), 'Max Christie', 'NBA', true),
  (gen_random_uuid(), 'P.J. Washington', 'NBA', true),
  (gen_random_uuid(), 'Klay Thompson', 'NBA', true),
  (gen_random_uuid(), 'Brandon Williams', 'NBA', true),
  (gen_random_uuid(), 'Daniel Gafford', 'NBA', true),
  (gen_random_uuid(), 'Ryan Nembhard', 'NBA', true),
  (gen_random_uuid(), 'Caleb Martin', 'NBA', true),
  (gen_random_uuid(), 'Dwight Powell', 'NBA', true),
  (gen_random_uuid(), 'Anthony Davis', 'NBA', true),
  (gen_random_uuid(), 'Khris Middleton', 'NBA', true),
  (gen_random_uuid(), 'D''Angelo Russell', 'NBA', true),
  (gen_random_uuid(), 'Moussa Cisse', 'NBA', true),
  (gen_random_uuid(), 'Miles Kelly', 'NBA', true),
  (gen_random_uuid(), 'Tyus Jones', 'NBA', true),
  (gen_random_uuid(), 'John Poulakidas', 'NBA', true),
  (gen_random_uuid(), 'Dereck Lively II', 'NBA', true),
  (gen_random_uuid(), 'Tyler Smith', 'NBA', true),
  (gen_random_uuid(), 'Jeremiah Robinson-Earl', 'NBA', true),
  (gen_random_uuid(), 'Kyrie Irving', 'NBA', true),
  (gen_random_uuid(), 'JaVale McGee', 'NBA', true),
  -- Denver Nuggets
  (gen_random_uuid(), 'Nikola Jokić', 'NBA', true),
  (gen_random_uuid(), 'Jamal Murray', 'NBA', true),
  (gen_random_uuid(), 'Aaron Gordon', 'NBA', true),
  (gen_random_uuid(), 'Peyton Watson', 'NBA', true),
  (gen_random_uuid(), 'Cameron Johnson', 'NBA', true),
  (gen_random_uuid(), 'Spencer Jones', 'NBA', true),
  (gen_random_uuid(), 'Christian Braun', 'NBA', true),
  (gen_random_uuid(), 'Bruce Brown', 'NBA', true),
  (gen_random_uuid(), 'Tim Hardaway Jr.', 'NBA', true),
  (gen_random_uuid(), 'Jonas Valančiūnas', 'NBA', true),
  (gen_random_uuid(), 'Julian Strawther', 'NBA', true),
  (gen_random_uuid(), 'Jalen Pickett', 'NBA', true),
  (gen_random_uuid(), 'Zeke Nnaji', 'NBA', true),
  (gen_random_uuid(), 'DaRon Holmes', 'NBA', true),
  (gen_random_uuid(), 'Hunter Tyson', 'NBA', true),
  -- Detroit Pistons
  (gen_random_uuid(), 'Cade Cunningham', 'NBA', true),
  (gen_random_uuid(), 'Jalen Duren', 'NBA', true),
  (gen_random_uuid(), 'Ausar Thompson', 'NBA', true),
  (gen_random_uuid(), 'Duncan Robinson', 'NBA', true),
  (gen_random_uuid(), 'Tobias Harris', 'NBA', true),
  (gen_random_uuid(), 'Ron Holland', 'NBA', true),
  (gen_random_uuid(), 'Isaiah Stewart', 'NBA', true),
  (gen_random_uuid(), 'Daniss Jenkins', 'NBA', true),
  (gen_random_uuid(), 'Caris LeVert', 'NBA', true),
  (gen_random_uuid(), 'Javonte Green', 'NBA', true),
  (gen_random_uuid(), 'Paul Reed', 'NBA', true),
  (gen_random_uuid(), 'Jaden Ivey', 'NBA', true),
  (gen_random_uuid(), 'Marcus Sasser', 'NBA', true),
  (gen_random_uuid(), 'Kevin Huerter', 'NBA', true),
  (gen_random_uuid(), 'Chaz Lanier', 'NBA', true),
  (gen_random_uuid(), 'Bobi Klintman', 'NBA', true),
  -- Golden State Warriors
  (gen_random_uuid(), 'Stephen Curry', 'NBA', true),
  (gen_random_uuid(), 'Jimmy Butler', 'NBA', true),
  (gen_random_uuid(), 'Kristaps Porziņģis', 'NBA', true),
  (gen_random_uuid(), 'Draymond Green', 'NBA', true),
  (gen_random_uuid(), 'Brandin Podziemski', 'NBA', true),
  (gen_random_uuid(), 'Moses Moody', 'NBA', true),
  (gen_random_uuid(), 'Will Richard', 'NBA', true),
  (gen_random_uuid(), 'Gui Santos', 'NBA', true),
  (gen_random_uuid(), 'Quinten Post', 'NBA', true),
  (gen_random_uuid(), 'Gary Payton II', 'NBA', true),
  (gen_random_uuid(), 'Buddy Hield', 'NBA', true),
  (gen_random_uuid(), 'Jonathan Kuminga', 'NBA', true),
  (gen_random_uuid(), 'Al Horford', 'NBA', true),
  (gen_random_uuid(), 'De''Anthony Melton', 'NBA', true),
  (gen_random_uuid(), 'Pat Spencer', 'NBA', true),
  (gen_random_uuid(), 'LJ Cryer', 'NBA', true),
  (gen_random_uuid(), 'Seth Curry', 'NBA', true),
  -- Houston Rockets
  (gen_random_uuid(), 'Kevin Durant', 'NBA', true),
  (gen_random_uuid(), 'Alperen Şengün', 'NBA', true),
  (gen_random_uuid(), 'Amen Thompson', 'NBA', true),
  (gen_random_uuid(), 'Jabari Smith Jr.', 'NBA', true),
  (gen_random_uuid(), 'Reed Sheppard', 'NBA', true),
  (gen_random_uuid(), 'Tari Eason', 'NBA', true),
  (gen_random_uuid(), 'Josh Okogie', 'NBA', true),
  (gen_random_uuid(), 'Clint Capela', 'NBA', true),
  (gen_random_uuid(), 'Aaron Holiday', 'NBA', true),
  (gen_random_uuid(), 'Dorian Finney-Smith', 'NBA', true),
  (gen_random_uuid(), 'Jae''Sean Tate', 'NBA', true),
  (gen_random_uuid(), 'Jeff Green', 'NBA', true),
  (gen_random_uuid(), 'Fred VanVleet', 'NBA', true),
  (gen_random_uuid(), 'JD Davison', 'NBA', true),
  -- Indiana Pacers
  (gen_random_uuid(), 'Tyrese Haliburton', 'NBA', true),
  (gen_random_uuid(), 'Pascal Siakam', 'NBA', true),
  (gen_random_uuid(), 'Andrew Nembhard', 'NBA', true),
  (gen_random_uuid(), 'Obi Toppin', 'NBA', true),
  (gen_random_uuid(), 'Aaron Nesmith', 'NBA', true),
  (gen_random_uuid(), 'T.J. McConnell', 'NBA', true),
  (gen_random_uuid(), 'Jarace Walker', 'NBA', true),
  (gen_random_uuid(), 'Jay Huff', 'NBA', true),
  (gen_random_uuid(), 'Ben Sheppard', 'NBA', true),
  (gen_random_uuid(), 'Quenton Jackson', 'NBA', true),
  (gen_random_uuid(), 'Kam Jones', 'NBA', true),
  (gen_random_uuid(), 'Taelon Peter', 'NBA', true),
  (gen_random_uuid(), 'Micah Potter', 'NBA', true),
  -- Los Angeles Clippers
  (gen_random_uuid(), 'Kawhi Leonard', 'NBA', true),
  (gen_random_uuid(), 'Darius Garland', 'NBA', true),
  (gen_random_uuid(), 'John Collins', 'NBA', true),
  (gen_random_uuid(), 'James Harden', 'NBA', true),
  (gen_random_uuid(), 'Brook Lopez', 'NBA', true),
  (gen_random_uuid(), 'Ivica Zubac', 'NBA', true),
  (gen_random_uuid(), 'Nicolas Batum', 'NBA', true),
  (gen_random_uuid(), 'Kobe Sanders', 'NBA', true),
  (gen_random_uuid(), 'Derrick Jones Jr.', 'NBA', true),
  (gen_random_uuid(), 'Bogdan Bogdanović', 'NBA', true),
  (gen_random_uuid(), 'Cam Christie', 'NBA', true),
  (gen_random_uuid(), 'Yanic Konan Niederhäuser', 'NBA', true),
  (gen_random_uuid(), 'Bennedict Mathurin', 'NBA', true),
  (gen_random_uuid(), 'Isaiah Jackson', 'NBA', true),
  (gen_random_uuid(), 'Kris Dunn', 'NBA', true),
  (gen_random_uuid(), 'Bradley Beal', 'NBA', true),
  (gen_random_uuid(), 'Chris Paul', 'NBA', true),
  (gen_random_uuid(), 'TyTy Washington Jr.', 'NBA', true),
  (gen_random_uuid(), 'Jordan Miller', 'NBA', true),
  (gen_random_uuid(), 'Kobe Brown', 'NBA', true),
  -- Los Angeles Lakers
  (gen_random_uuid(), 'LeBron James', 'NBA', true),
  (gen_random_uuid(), 'Luka Dončić', 'NBA', true),
  (gen_random_uuid(), 'Deandre Ayton', 'NBA', true),
  (gen_random_uuid(), 'Rui Hachimura', 'NBA', true),
  (gen_random_uuid(), 'Austin Reaves', 'NBA', true),
  (gen_random_uuid(), 'Jarred Vanderbilt', 'NBA', true),
  (gen_random_uuid(), 'Maxi Kleber', 'NBA', true),
  (gen_random_uuid(), 'Luke Kennard', 'NBA', true),
  (gen_random_uuid(), 'Jake LaRavia', 'NBA', true),
  (gen_random_uuid(), 'Marcus Smart', 'NBA', true),
  (gen_random_uuid(), 'Dalton Knecht', 'NBA', true),
  (gen_random_uuid(), 'Jaxson Hayes', 'NBA', true),
  (gen_random_uuid(), 'Bronny James', 'NBA', true),
  (gen_random_uuid(), 'Gabe Vincent', 'NBA', true),
  (gen_random_uuid(), 'Adou Thiero', 'NBA', true),
  (gen_random_uuid(), 'Kobe Bufkin', 'NBA', true),
  -- Memphis Grizzlies
  (gen_random_uuid(), 'Ja Morant', 'NBA', true),
  (gen_random_uuid(), 'Jaylen Wells', 'NBA', true),
  (gen_random_uuid(), 'Cam Spencer', 'NBA', true),
  (gen_random_uuid(), 'Cedric Coward', 'NBA', true),
  (gen_random_uuid(), 'Jaren Jackson Jr.', 'NBA', true),
  (gen_random_uuid(), 'Santi Aldama', 'NBA', true),
  (gen_random_uuid(), 'GG Jackson II', 'NBA', true),
  (gen_random_uuid(), 'Kentavious Caldwell-Pope', 'NBA', true),
  (gen_random_uuid(), 'Jock Landale', 'NBA', true),
  (gen_random_uuid(), 'Javon Small', 'NBA', true),
  (gen_random_uuid(), 'Olivier-Maxence Prosper', 'NBA', true),
  (gen_random_uuid(), 'John Konchar', 'NBA', true),
  (gen_random_uuid(), 'Vince Williams Jr.', 'NBA', true),
  (gen_random_uuid(), 'Scotty Pippen Jr.', 'NBA', true),
  (gen_random_uuid(), 'Ty Jerome', 'NBA', true),
  (gen_random_uuid(), 'Zach Edey', 'NBA', true),
  (gen_random_uuid(), 'Christian Koloko', 'NBA', true),
  (gen_random_uuid(), 'Jahmai Mashack', 'NBA', true),
  (gen_random_uuid(), 'DeJon Jarreau', 'NBA', true),
  (gen_random_uuid(), 'Rayan Rupert', 'NBA', true),
  (gen_random_uuid(), 'Tyler Burton', 'NBA', true),
  (gen_random_uuid(), 'Brandon Clarke', 'NBA', true),
  (gen_random_uuid(), 'Dariq Whitehead', 'NBA', true),
  (gen_random_uuid(), 'Lawson Lovering', 'NBA', true),
  (gen_random_uuid(), 'PJ Hall', 'NBA', true),
  (gen_random_uuid(), 'Charles Bassey', 'NBA', true),
  (gen_random_uuid(), 'Cole Anthony', 'NBA', true),
  (gen_random_uuid(), 'Georges Niang', 'NBA', true),
  (gen_random_uuid(), 'Eric Gordon', 'NBA', true),
  -- Miami Heat
  (gen_random_uuid(), 'Bam Adebayo', 'NBA', true),
  (gen_random_uuid(), 'Tyler Herro', 'NBA', true),
  (gen_random_uuid(), 'Andrew Wiggins', 'NBA', true),
  (gen_random_uuid(), 'Terry Rozier', 'NBA', true),
  (gen_random_uuid(), 'Norman Powell', 'NBA', true),
  (gen_random_uuid(), 'Davion Mitchell', 'NBA', true),
  (gen_random_uuid(), 'Simone Fontecchio', 'NBA', true),
  (gen_random_uuid(), 'Nikola Jović', 'NBA', true),
  (gen_random_uuid(), 'Kel''el Ware', 'NBA', true),
  (gen_random_uuid(), 'Jaime Jaquez Jr.', 'NBA', true),
  (gen_random_uuid(), 'Kasparas Jakučionis', 'NBA', true),
  (gen_random_uuid(), 'Dru Smith', 'NBA', true),
  (gen_random_uuid(), 'Pelle Larsson', 'NBA', true),
  (gen_random_uuid(), 'Keshad Johnson', 'NBA', true),
  (gen_random_uuid(), 'Myron Gardner', 'NBA', true),
  -- Milwaukee Bucks
  (gen_random_uuid(), 'Giannis Antetokounmpo', 'NBA', true),
  (gen_random_uuid(), 'Damian Lillard', 'NBA', true),
  (gen_random_uuid(), 'Myles Turner', 'NBA', true),
  (gen_random_uuid(), 'Kyle Kuzma', 'NBA', true),
  (gen_random_uuid(), 'Bobby Portis', 'NBA', true),
  (gen_random_uuid(), 'Ryan Rollins', 'NBA', true),
  (gen_random_uuid(), 'A.J. Green', 'NBA', true),
  (gen_random_uuid(), 'Jericho Sims', 'NBA', true),
  (gen_random_uuid(), 'Kevin Porter Jr.', 'NBA', true),
  (gen_random_uuid(), 'Gary Trent Jr.', 'NBA', true),
  (gen_random_uuid(), 'Pete Nance', 'NBA', true),
  (gen_random_uuid(), 'Gary Harris', 'NBA', true),
  (gen_random_uuid(), 'Andre Jackson Jr.', 'NBA', true),
  (gen_random_uuid(), 'Taurean Prince', 'NBA', true),
  (gen_random_uuid(), 'Thanasis Antetokounmpo', 'NBA', true),
  -- Minnesota Timberwolves
  (gen_random_uuid(), 'Anthony Edwards', 'NBA', true),
  (gen_random_uuid(), 'Julius Randle', 'NBA', true),
  (gen_random_uuid(), 'Rudy Gobert', 'NBA', true),
  (gen_random_uuid(), 'Donte DiVincenzo', 'NBA', true),
  (gen_random_uuid(), 'Jaden McDaniels', 'NBA', true),
  (gen_random_uuid(), 'Naz Reid', 'NBA', true),
  (gen_random_uuid(), 'Bones Hyland', 'NBA', true),
  (gen_random_uuid(), 'Mike Conley', 'NBA', true),
  (gen_random_uuid(), 'Ayo Dosunmu', 'NBA', true),
  (gen_random_uuid(), 'Jaylen Clark', 'NBA', true),
  (gen_random_uuid(), 'Terrence Shannon Jr.', 'NBA', true),
  (gen_random_uuid(), 'Rob Dillingham', 'NBA', true),
  (gen_random_uuid(), 'Joan Beringer', 'NBA', true),
  (gen_random_uuid(), 'Joe Ingles', 'NBA', true),
  (gen_random_uuid(), 'Johnny Juzang', 'NBA', true),
  (gen_random_uuid(), 'Julian Phillips', 'NBA', true),
  (gen_random_uuid(), 'Leonard Miller', 'NBA', true),
  (gen_random_uuid(), 'Walker Kessler', 'NBA', true),
  -- New Orleans Pelicans
  (gen_random_uuid(), 'Zion Williamson', 'NBA', true),
  (gen_random_uuid(), 'Jordan Poole', 'NBA', true),
  (gen_random_uuid(), 'Dejounte Murray', 'NBA', true),
  (gen_random_uuid(), 'Trey Murphy III', 'NBA', true),
  (gen_random_uuid(), 'Herbert Jones', 'NBA', true),
  (gen_random_uuid(), 'Jeremiah Fears', 'NBA', true),
  (gen_random_uuid(), 'Saddiq Bey', 'NBA', true),
  (gen_random_uuid(), 'Derik Queen', 'NBA', true),
  (gen_random_uuid(), 'Bryce McGowens', 'NBA', true),
  (gen_random_uuid(), 'Micah Peavy', 'NBA', true),
  (gen_random_uuid(), 'Jordan Hawkins', 'NBA', true),
  (gen_random_uuid(), 'Kevon Looney', 'NBA', true),
  (gen_random_uuid(), 'DeAndre Jordan', 'NBA', true),
  (gen_random_uuid(), 'Yves Missi', 'NBA', true),
  (gen_random_uuid(), 'Dalen Terry', 'NBA', true),
  (gen_random_uuid(), 'Karlo Matković', 'NBA', true),
  (gen_random_uuid(), 'Jaden Springer', 'NBA', true),
  -- New York Knicks
  (gen_random_uuid(), 'Jalen Brunson', 'NBA', true),
  (gen_random_uuid(), 'Karl-Anthony Towns', 'NBA', true),
  (gen_random_uuid(), 'OG Anunoby', 'NBA', true),
  (gen_random_uuid(), 'Mikal Bridges', 'NBA', true),
  (gen_random_uuid(), 'Josh Hart', 'NBA', true),
  (gen_random_uuid(), 'Jordan Clarkson', 'NBA', true),
  (gen_random_uuid(), 'Mitchell Robinson', 'NBA', true),
  (gen_random_uuid(), 'Landry Shamet', 'NBA', true),
  (gen_random_uuid(), 'Miles McBride', 'NBA', true),
  (gen_random_uuid(), 'Tyler Kolek', 'NBA', true),
  (gen_random_uuid(), 'Pacôme Dadiet', 'NBA', true),
  (gen_random_uuid(), 'Jose Alvarado', 'NBA', true),
  (gen_random_uuid(), 'Ariel Hukporti', 'NBA', true),
  (gen_random_uuid(), 'Kevin McCullar Jr.', 'NBA', true),
  -- Oklahoma City Thunder
  (gen_random_uuid(), 'Shai Gilgeous-Alexander', 'NBA', true),
  (gen_random_uuid(), 'Chet Holmgren', 'NBA', true),
  (gen_random_uuid(), 'Cason Wallace', 'NBA', true),
  (gen_random_uuid(), 'Jalen Williams', 'NBA', true),
  (gen_random_uuid(), 'Isaiah Joe', 'NBA', true),
  (gen_random_uuid(), 'Ajay Mitchell', 'NBA', true),
  (gen_random_uuid(), 'Aaron Wiggins', 'NBA', true),
  (gen_random_uuid(), 'Jaylin Williams', 'NBA', true),
  (gen_random_uuid(), 'Isaiah Hartenstein', 'NBA', true),
  (gen_random_uuid(), 'Alex Caruso', 'NBA', true),
  (gen_random_uuid(), 'Jared McCain', 'NBA', true),
  (gen_random_uuid(), 'Branden Carlson', 'NBA', true),
  (gen_random_uuid(), 'Ousmane Dieng', 'NBA', true),
  (gen_random_uuid(), 'Nikola Topić', 'NBA', true),
  (gen_random_uuid(), 'Thomas Sorber', 'NBA', true),
  (gen_random_uuid(), 'Kenrich Williams', 'NBA', true),
  (gen_random_uuid(), 'Luguentz Dort', 'NBA', true),
  (gen_random_uuid(), 'Mason Plumlee', 'NBA', true),
  -- Orlando Magic
  (gen_random_uuid(), 'Desmond Bane', 'NBA', true),
  (gen_random_uuid(), 'Paolo Banchero', 'NBA', true),
  (gen_random_uuid(), 'Wendell Carter Jr.', 'NBA', true),
  (gen_random_uuid(), 'Jalen Suggs', 'NBA', true),
  (gen_random_uuid(), 'Anthony Black', 'NBA', true),
  (gen_random_uuid(), 'Tristan Da Silva', 'NBA', true),
  (gen_random_uuid(), 'Franz Wagner', 'NBA', true),
  (gen_random_uuid(), 'Goga Bitadze', 'NBA', true),
  (gen_random_uuid(), 'Noah Penda', 'NBA', true),
  (gen_random_uuid(), 'Jett Howard', 'NBA', true),
  (gen_random_uuid(), 'Jase Richardson', 'NBA', true),
  (gen_random_uuid(), 'Jevon Carter', 'NBA', true),
  (gen_random_uuid(), 'Jonathan Isaac', 'NBA', true),
  (gen_random_uuid(), 'Moritz Wagner', 'NBA', true),
  (gen_random_uuid(), 'Jamal Cain', 'NBA', true),
  -- Philadelphia 76ers
  (gen_random_uuid(), 'Tyrese Maxey', 'NBA', true),
  (gen_random_uuid(), 'Joel Embiid', 'NBA', true),
  (gen_random_uuid(), 'Paul George', 'NBA', true),
  (gen_random_uuid(), 'VJ Edgecombe', 'NBA', true),
  (gen_random_uuid(), 'Quentin Grimes', 'NBA', true),
  (gen_random_uuid(), 'Kelly Oubre Jr.', 'NBA', true),
  (gen_random_uuid(), 'Andre Drummond', 'NBA', true),
  (gen_random_uuid(), 'Dominick Barlow', 'NBA', true),
  (gen_random_uuid(), 'Trendon Watford', 'NBA', true),
  (gen_random_uuid(), 'Justin Edwards', 'NBA', true),
  (gen_random_uuid(), 'Jabari Walker', 'NBA', true),
  (gen_random_uuid(), 'Cameron Payne', 'NBA', true),
  (gen_random_uuid(), 'Kyle Lowry', 'NBA', true),
  (gen_random_uuid(), 'Adem Bona', 'NBA', true),
  -- Phoenix Suns
  (gen_random_uuid(), 'Devin Booker', 'NBA', true),
  (gen_random_uuid(), 'Collin Gillespie', 'NBA', true),
  (gen_random_uuid(), 'Royce O''Neale', 'NBA', true),
  (gen_random_uuid(), 'Oso Ighodaro', 'NBA', true),
  (gen_random_uuid(), 'Dillon Brooks', 'NBA', true),
  (gen_random_uuid(), 'Jordan Goodwin', 'NBA', true),
  (gen_random_uuid(), 'Grayson Allen', 'NBA', true),
  (gen_random_uuid(), 'Mark Williams', 'NBA', true),
  (gen_random_uuid(), 'Ryan Dunn', 'NBA', true),
  (gen_random_uuid(), 'Jalen Green', 'NBA', true),
  (gen_random_uuid(), 'Rasheer Fleming', 'NBA', true),
  (gen_random_uuid(), 'Jamaree Bouyea', 'NBA', true),
  (gen_random_uuid(), 'Khaman Maluach', 'NBA', true),
  (gen_random_uuid(), 'Nick Richards', 'NBA', true),
  (gen_random_uuid(), 'Isaiah Livers', 'NBA', true),
  (gen_random_uuid(), 'Nassir Little', 'NBA', true),
  (gen_random_uuid(), 'Amir Coffey', 'NBA', true),
  (gen_random_uuid(), 'Haywood Highsmith', 'NBA', true),
  -- Portland Trail Blazers
  (gen_random_uuid(), 'Deni Avdija', 'NBA', true),
  (gen_random_uuid(), 'Donovan Clingan', 'NBA', true),
  (gen_random_uuid(), 'Jerami Grant', 'NBA', true),
  (gen_random_uuid(), 'Jrue Holiday', 'NBA', true),
  (gen_random_uuid(), 'Shaedon Sharpe', 'NBA', true),
  (gen_random_uuid(), 'Toumani Camara', 'NBA', true),
  (gen_random_uuid(), 'Sidy Cissoko', 'NBA', true),
  (gen_random_uuid(), 'Kris Murray', 'NBA', true),
  (gen_random_uuid(), 'Caleb Love', 'NBA', true),
  (gen_random_uuid(), 'Robert Williams', 'NBA', true),
  (gen_random_uuid(), 'Scoot Henderson', 'NBA', true),
  (gen_random_uuid(), 'Matisse Thybulle', 'NBA', true),
  (gen_random_uuid(), 'Vít Krejčí', 'NBA', true),
  (gen_random_uuid(), 'Yang Hansen', 'NBA', true),
  (gen_random_uuid(), 'Duop Reath', 'NBA', true),
  -- Sacramento Kings
  (gen_random_uuid(), 'DeMar DeRozan', 'NBA', true),
  (gen_random_uuid(), 'Russell Westbrook', 'NBA', true),
  (gen_random_uuid(), 'Maxime Raynaud', 'NBA', true),
  (gen_random_uuid(), 'Nique Clifford', 'NBA', true),
  (gen_random_uuid(), 'Precious Achiuwa', 'NBA', true),
  (gen_random_uuid(), 'Malik Monk', 'NBA', true),
  (gen_random_uuid(), 'Zach LaVine', 'NBA', true),
  (gen_random_uuid(), 'Dennis Schröder', 'NBA', true),
  (gen_random_uuid(), 'Keon Ellis', 'NBA', true),
  (gen_random_uuid(), 'Daeqwon Plowden', 'NBA', true),
  (gen_random_uuid(), 'Devin Carter', 'NBA', true),
  (gen_random_uuid(), 'Domantas Sabonis', 'NBA', true),
  (gen_random_uuid(), 'Drew Eubanks', 'NBA', true),
  (gen_random_uuid(), 'Doug McDermott', 'NBA', true),
  (gen_random_uuid(), 'Dylan Cardwell', 'NBA', true),
  (gen_random_uuid(), 'Keegan Murray', 'NBA', true),
  (gen_random_uuid(), 'De''Andre Hunter', 'NBA', true),
  (gen_random_uuid(), 'Killian Hayes', 'NBA', true),
  -- San Antonio Spurs
  (gen_random_uuid(), 'Victor Wembanyama', 'NBA', true),
  (gen_random_uuid(), 'De''Aaron Fox', 'NBA', true),
  (gen_random_uuid(), 'Devin Vassell', 'NBA', true),
  (gen_random_uuid(), 'Stephon Castle', 'NBA', true),
  (gen_random_uuid(), 'Dylan Harper', 'NBA', true),
  (gen_random_uuid(), 'Julian Champagnie', 'NBA', true),
  (gen_random_uuid(), 'Keldon Johnson', 'NBA', true),
  (gen_random_uuid(), 'Harrison Barnes', 'NBA', true),
  (gen_random_uuid(), 'Luke Kornet', 'NBA', true),
  (gen_random_uuid(), 'Carter Bryant', 'NBA', true),
  (gen_random_uuid(), 'Kelly Olynyk', 'NBA', true),
  (gen_random_uuid(), 'Jeremy Sochan', 'NBA', true),
  (gen_random_uuid(), 'Jordan McLaughlin', 'NBA', true),
  (gen_random_uuid(), 'Lindy Waters III', 'NBA', true),
  (gen_random_uuid(), 'Bismack Biyombo', 'NBA', true),
  -- Toronto Raptors
  (gen_random_uuid(), 'Scottie Barnes', 'NBA', true),
  (gen_random_uuid(), 'Brandon Ingram', 'NBA', true),
  (gen_random_uuid(), 'Immanuel Quickley', 'NBA', true),
  (gen_random_uuid(), 'RJ Barrett', 'NBA', true),
  (gen_random_uuid(), 'Jakob Poeltl', 'NBA', true),
  (gen_random_uuid(), 'Gradey Dick', 'NBA', true),
  (gen_random_uuid(), 'Ja''Kobe Walter', 'NBA', true),
  (gen_random_uuid(), 'Sandro Mamukelashvili', 'NBA', true),
  (gen_random_uuid(), 'Jamal Shead', 'NBA', true),
  (gen_random_uuid(), 'Collin Murray-Boyles', 'NBA', true),
  (gen_random_uuid(), 'Jamison Battle', 'NBA', true),
  (gen_random_uuid(), 'Garrett Temple', 'NBA', true),
  (gen_random_uuid(), 'Jonathan Mogbo', 'NBA', true),
  (gen_random_uuid(), 'Trayce Jackson-Davis', 'NBA', true),
  -- Utah Jazz
  (gen_random_uuid(), 'Lauri Markkanen', 'NBA', true),
  (gen_random_uuid(), 'Ace Bailey', 'NBA', true),
  (gen_random_uuid(), 'Keyonte George', 'NBA', true),
  (gen_random_uuid(), 'Kyle Filipowski', 'NBA', true),
  (gen_random_uuid(), 'Brice Sensabaugh', 'NBA', true),
  (gen_random_uuid(), 'Isaiah Collier', 'NBA', true),
  (gen_random_uuid(), 'Cody Williams', 'NBA', true),
  (gen_random_uuid(), 'Svi Mykhailiuk', 'NBA', true),
  (gen_random_uuid(), 'Jusuf Nurkić', 'NBA', true),
  (gen_random_uuid(), 'Walter Clayton', 'NBA', true),
  (gen_random_uuid(), 'Kevin Love', 'NBA', true),
  (gen_random_uuid(), 'Kyle Anderson', 'NBA', true),
  (gen_random_uuid(), 'Taylor Hendricks', 'NBA', true),
  (gen_random_uuid(), 'Bez Mbeng', 'NBA', true),
  (gen_random_uuid(), 'Oscar Tshiebwe', 'NBA', true),
  (gen_random_uuid(), 'Kennedy Chandler', 'NBA', true),
  (gen_random_uuid(), 'Mo Bamba', 'NBA', true),
  (gen_random_uuid(), 'Lonzo Ball', 'NBA', true),
  (gen_random_uuid(), 'Chris Boucher', 'NBA', true),
  (gen_random_uuid(), 'Elijah Harkless', 'NBA', true),
  -- Washington Wizards
  (gen_random_uuid(), 'Bub Carrington', 'NBA', true),
  (gen_random_uuid(), 'Will Riley', 'NBA', true),
  (gen_random_uuid(), 'Tre Johnson', 'NBA', true),
  (gen_random_uuid(), 'Bilal Coulibaly', 'NBA', true),
  (gen_random_uuid(), 'Kyshawn George', 'NBA', true),
  (gen_random_uuid(), 'Alex Sarr', 'NBA', true),
  (gen_random_uuid(), 'Justin Champagnie', 'NBA', true),
  (gen_random_uuid(), 'CJ McCollum', 'NBA', true),
  (gen_random_uuid(), 'Jamir Watkins', 'NBA', true),
  (gen_random_uuid(), 'Anthony Gill', 'NBA', true),
  (gen_random_uuid(), 'Jaden Hardy', 'NBA', true),
  (gen_random_uuid(), 'Corey Kispert', 'NBA', true),
  (gen_random_uuid(), 'Cam Whitmore', 'NBA', true),
  (gen_random_uuid(), 'Leaky Black', 'NBA', true),
  (gen_random_uuid(), 'Malaki Branham', 'NBA', true),
  (gen_random_uuid(), 'Julian Reese', 'NBA', true),
  (gen_random_uuid(), 'AJ Johnson', 'NBA', true),
  (gen_random_uuid(), 'Trae Young', 'NBA', true),
  (gen_random_uuid(), 'Blake Wesley', 'NBA', true),
  (gen_random_uuid(), 'Dillon Jones', 'NBA', true),
  (gen_random_uuid(), 'Danté Exum', 'NBA', true),
  (gen_random_uuid(), 'Keshon Gilbert', 'NBA', true),
  (gen_random_uuid(), 'Kadary Richmond', 'NBA', true),
  (gen_random_uuid(), 'Alondes Williams', 'NBA', true),
  (gen_random_uuid(), 'Marvin Bagley III', 'NBA', true),
  (gen_random_uuid(), 'Skal Labissière', 'NBA', true);
